// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlackBall: typeof import('./src/components/BlackBall.vue')['default']
    BlackBox: typeof import('./src/components/BlackBox.vue')['default']
    Confetti: typeof import('./src/components/Confetti.vue')['default']
    LighterBtn: typeof import('./src/components/LighterBtn.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
  }
}
